export const GameConstant = Object.freeze({
    GAME_WIDTH: 720,
    GAME_HEIGHT: 1280,

    KNIFE_X_POSITION: 360,
    KNIFE_Y_POSITION: 950,  
    KNIFE_P1_Y_POSITION: 1110,
    KNIFE_P2_Y_POSITION: 170,

    BOARD_X_POSITION: 360,
    BOARD_Y_POSITION: 386,
    BOARD_DUAL_Y_POSITION: 640,

    JUMP_TIMER: 20,
    JUMP_DISTANCE: 10,

    DEBUG_DRAW_COLLIDER: false,
  })